import os


SECRET_KEY = os.environ['SECRET_KEY']
DEBUG = int(os.environ.get('DEBUG', 0))

DEFAULT_DB = 'default'
DEFAULT_DB_DATABASE_NAME = os.environ['DEFAULT_DB_DATABASE_NAME']
DEFAULT_DB_DATABASE_USER = os.environ['DEFAULT_DB_DATABASE_USER']
DEFAULT_DB_DATABASE_PASS = os.environ['DEFAULT_DB_DATABASE_PASS']
DEFAULT_DB_DATABASE_HOST = os.environ['DEFAULT_DB_DATABASE_HOST']
DEFAULT_DB_DATABASE_PORT = os.environ['DEFAULT_DB_DATABASE_PORT']
